# Generated by Django 3.1 on 2021-01-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('project_link', models.URLField(null=True)),
                ('front_image', models.ImageField(blank=True, upload_to='proj_frontimages', verbose_name='Thumbnail')),
                ('technical_details', models.TextField(null=True, verbose_name='Technical Details')),
            ],
        ),
    ]
