# Generated by Django 3.1.5 on 2021-01-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_projectupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
