# Generated by Django 3.1.5 on 2021-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0003_auto_20210114_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='page_url',
            field=models.URLField(default='123.com'),
            preserve_default=False,
        ),
    ]
