# Generated by Django 3.1.5 on 2021-01-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0004_auto_20210114_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='page_url',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
