# Generated by Django 3.1.5 on 2021-01-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0006_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='front_image',
            field=models.ImageField(upload_to='proj_frontimages', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
