# Generated by Django 3.1.5 on 2021-01-16 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0009_auto_20210115_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='large_image',
            field=models.ImageField(blank=True, upload_to='proj_frontimages'),
        ),
    ]
