# Generated by Django 3.1.5 on 2021-01-16 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0010_auto_20210115_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
