# Generated by Django 3.1.5 on 2021-01-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0011_auto_20210115_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technical_details',
            field=models.TextField(null=True, verbose_name='Technical Details (split by line)'),
        ),
    ]
