# Generated by Django 3.1.5 on 2021-01-16 22:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0012_auto_20210116_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_hero_text', models.TextField()),
                ('about_page_description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(null=True),
        ),
    ]
