# Generated by Django 3.1.5 on 2021-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0013_auto_20210116_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinformation',
            name='email',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
