# Generated by Django 3.1.5 on 2021-01-16 22:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0014_auto_20210116_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
