#Generated by Django 3.1.5 on 2021-01-16 22:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprojects', '0015_auto_20210116_1430'),
    ]

    operations = [
        
    ]
