# Generated by Django 3.1.5 on 2021-01-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0016_myinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinformation',
            name='user',
        ),
    ]
