# Generated by Django 3.1.5 on 2021-01-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0017_remove_myinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='email',
            field=models.EmailField(default='123@j.com', max_length=254),
        ),
    ]
