# Generated by Django 3.1.5 on 2021-01-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0018_myinformation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
