# Generated by Django 3.1.5 on 2021-01-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0019_auto_20210116_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(null=True, verbose_name='Key Features (split by line)'),
        ),
    ]
