# Generated by Django 3.1.5 on 2021-03-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0020_project_key_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='current_role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myinformation',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinformation',
            name='linked_in_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinformation',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myinformation',
            name='my_photo',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='myinformation',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myinformation',
            name='tech_stack',
            field=models.TextField(null=True, verbose_name='Stack (split by line)'),
        ),
    ]
