# Generated by Django 3.1.5 on 2021-03-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0021_auto_20210306_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myinformation',
            old_name='linked_in_url',
            new_name='linkedin_url',
        ),
        migrations.AddField(
            model_name='myinformation',
            name='name',
            field=models.CharField(default='Jiaqi Wang', max_length=20),
            preserve_default=False,
        ),
    ]
