# Generated by Django 3.1.5 on 2021-03-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0022_auto_20210306_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='tech_stack',
            field=models.TextField(null=True, verbose_name='Stack (split by /)'),
        ),
    ]
