# Generated by Django 3.1.5 on 2021-03-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0024_auto_20210307_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeatureList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=50)),
                ('feature_detial', models.TextField()),
                ('feature_image', models.ImageField(blank=True, upload_to='feature_images')),
            ],
        ),
    ]
