# Generated by Django 3.1.5 on 2021-03-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0025_projectfeaturelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeaturelist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojects.project'),
            preserve_default=False,
        ),
    ]
