# Generated by Django 3.1.5 on 2021-03-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0026_projectfeaturelist_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfeaturelist',
            old_name='feature_detial',
            new_name='feature_detail',
        ),
    ]
