# Generated by Django 3.1.5 on 2021-03-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0027_auto_20210308_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
