# Generated by Django 3.1.5 on 2021-03-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0028_project_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=50)),
                ('sample_text', models.TextField()),
                ('github_gist_url', models.URLField()),
                ('feature_image', models.ImageField(null=True, upload_to='code sample')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprojects.project')),
            ],
        ),
    ]
