# Generated by Django 3.1.5 on 2021-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0030_auto_20210312_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesample',
            name='github_gist_id',
        ),
        migrations.AddField(
            model_name='codesample',
            name='github_gist_url',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
