# Generated by Django 3.1.5 on 2021-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0031_auto_20210312_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesample',
            name='github_gist_url',
        ),
        migrations.AddField(
            model_name='codesample',
            name='github_gist_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
